type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  profilePictureUrl: String
}

type Stamp @table {
  name: String!
  country: String!
  yearOfIssue: Int!
  createdAt: Timestamp!
  description: String
  catalogNumber: String
  condition: String
  faceValue: Float
  purchasePrice: Float
  currentValue: Float
  imageUrl: String
  owner: User
}

type Collection @table {
  name: String!
  isPublic: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
  owner: User
}

type CollectionStamp @table(key: ["collection", "stamp"]) {
  collection: Collection!
  stamp: Stamp!
  addedAt: Timestamp!
  note: String
}